[package]
name = "sqlite-web"
version = "0.0.2"
edition = "2021"
repository = "https://github.com/rainlanguage/sqlite-web"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true }
base64 = { workspace = true }
wasm-bindgen-utils = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[features]
default = []

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
serde_json = { workspace = true }
